from collections import namedtuple

Genotype = namedtuple('Genotype', 'normal normal_concat')

PRIMITIVES = [
    'avg_pool_3',
    'avg_pool_5',
    'avg_pool_7',
    'max_pool_3',
    'max_pool_5',
    'max_pool_7',
    'lp_pool_3',
    'lp_pool_5',
    'lp_pool_7',
    'skip_connect',
    'g_conv_3_RELU',
    'g_conv_3_ELU',
    'g_conv_3_LeakyReLU',
    'g_conv_5_RELU',
    'g_conv_5_ELU',
    'g_conv_5_LeakyReLU',
    'g_conv_7_RELU',
    'g_conv_7_ELU',
    'g_conv_7_LeakyReLU',
    'dilg_conv_3_RELU',
    'dilg_conv_3_ELU',
    'dilg_conv_3_LeakyReLU',
    'dilg_conv_5_RELU',
    'dilg_conv_5_ELU',
    'dilg_conv_5_LeakyReLU',
    'dilg_conv_7_RELU',
    'dilg_conv_7_ELU',
    'dilg_conv_7_LeakyReLU',
    'conv_3_RELU',
    'conv_3_ELU',
    'conv_3_LeakyReLU',
    'conv_5_RELU',
    'conv_5_ELU',
    'conv_5_LeakyReLU',
    'conv_7_RELU',
    'conv_7_ELU',
    'conv_7_LeakyReLU',
]
